import { OrderItemType } from './invoice.model';
import { generateOrderName, Invoice } from 'app/shared/model/invoice.model';

export interface CartItem {
    selection: string;
}

export interface Product {
    title: string;
    type: OrderItemType;
    price: number;
    options: string[];
    cart: CartItem[];
}

const LARGE_BEER: Product = {
    title: 'Large',
    type: OrderItemType.LARGE_BEER,
    price: 2.0,
    options: ['"Lightning Ale"', '"Block Brew"'],
    cart: []
};
const SMALL_BEER: Product = {
    title: 'Small',
    type: OrderItemType.SMALL_BEER,
    price: 1.0,
    options: ['"Coin Stout"', '"Thunderous Amber"'],
    cart: []
};
const PRODUCTS: Product[] = [LARGE_BEER, SMALL_BEER];

export function clone(obj) {
    return JSON.parse(JSON.stringify(obj));
}

export function getProducts() {
    return clone(PRODUCTS);
}

export function getProductByType(type: OrderItemType): Product {
    return getProducts().filter(p => p.type === type)[0] || {};
}

export function getTitleByType(type: OrderItemType): string {
    return getProductByType(type).title;
}

export function getPriceByType(type: OrderItemType): string {
    return (<any>getProductByType(type)).price;
}

export function getSelfServiceOrders(landscape = false): Invoice[] {
    return (landscape ? getSelfServiceLandscapeItems() : getSelfServiceItems()).map(item => ({
        orderName: generateOrderName(),
        orderItems: [item],
        autoGenerated: true
    }));
}

export function getSelfServiceItems() {
    return [
        {
            itemType: OrderItemType.LARGE_BEER,
            count: 1,
            options: ['"Lightning Ale"']
        },
        {
            itemType: OrderItemType.LARGE_BEER,
            count: 1,
            options: ['"Block Brew"']
        },
        {
            itemType: OrderItemType.SMALL_BEER,
            count: 1,
            options: ['"Coin Stout"']
        },
        {
            itemType: OrderItemType.SMALL_BEER,
            count: 1,
            options: ['"Thunderous Amber"']
        }
    ];
}

export function getSelfServiceLandscapeItems() {
    return [
        {
            itemType: OrderItemType.LARGE_BEER,
            count: 1,
            options: ['"Block Brew"']
        },
        {
            itemType: OrderItemType.SMALL_BEER,
            count: 1,
            options: ['"Coin Stout"']
        }
    ];
}
