package ch.puzzle.ln.pos.repository;

import ch.puzzle.ln.pos.domain.Invoice;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

@SuppressWarnings("unused")
@Repository
public interface InvoiceRepository extends JpaRepository<Invoice, Long> {

    Invoice findByHashHex(String hashHex);

    List<Invoice> findAllByAutoGeneratedTrueAndSettledFalseAndCreationDateLessThan(Instant creationDate);
}
